// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.21.0-rc.4";

// src/lib/mcp/tools/get-plan-overview.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.21.0-rc.4";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_plan_overview_default = defineTool({
  name: "get_plan_overview",
  title: "Get plan overview",
  description: "Return the signed-in user's current financial plan: mode (individual or couple), goal amount, timeframe, monthly contribution, and the active participants.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: plan, error: planError } = await client.from("plans").select(
      "id, mode, goal_amount, goal_years, goal_purpose, initial_amount, monthly_contribution, onboarding_complete"
    ).eq("user_id", userId).order("created_at", { ascending: true }).limit(1).maybeSingle();
    if (planError) {
      return { content: [{ type: "text", text: planError.message }], isError: true };
    }
    if (!plan) {
      return {
        content: [{ type: "text", text: "No plan configured yet." }],
        structuredContent: { plan: null, members: [] }
      };
    }
    const { data: members, error: membersError } = await client.from("plan_members").select("id, name, role, is_primary, age").eq("plan_id", plan.id).eq("is_active", true).order("is_primary", { ascending: false });
    if (membersError) {
      return { content: [{ type: "text", text: membersError.message }], isError: true };
    }
    const summary = {
      mode: plan.mode,
      goal_amount: plan.goal_amount,
      goal_years: plan.goal_years,
      goal_purpose: plan.goal_purpose,
      initial_amount: plan.initial_amount,
      monthly_contribution: plan.monthly_contribution,
      onboarding_complete: plan.onboarding_complete,
      members: members ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-assets.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.21.0-rc.4";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_assets_default = defineTool2({
  name: "list_assets",
  title: "List investments",
  description: "List the signed-in user's active investments (assets) with type, institution, invested amount, current amount, bucket, FGC coverage and liquidity, plus totals.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("assets").select(
      "id, asset_type, asset_subtype, ticker_or_name, institution, conglomerate, bucket, has_fgc, has_sovereign_guarantee, liquidity_type, invested_amount, current_amount, maturity_date"
    ).eq("user_id", ctx.getUserId()).eq("is_active", true).order("current_amount", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const assets = data ?? [];
    const total_invested = assets.reduce((sum, a) => sum + Number(a.invested_amount ?? 0), 0);
    const total_current = assets.reduce((sum, a) => sum + Number(a.current_amount ?? 0), 0);
    const payload = { count: assets.length, total_invested, total_current, assets };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-monthly-tracking.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.21.0-rc.4";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_monthly_tracking_default = defineTool3({
  name: "list_monthly_tracking",
  title: "List monthly tracking",
  description: "Return the most recent months of the signed-in user's monthly deposit tracking: month, planned total, actual total, shortfall, and status.",
  inputSchema: {
    limit: z.number().int().min(1).max(60).optional().describe("How many recent months to return. Defaults to 12.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("monthly_tracking").select("month_key, year, month, planned_total, actual_total, shortfall, status, notes").eq("user_id", ctx.getUserId()).order("month_key", { ascending: false }).limit(limit ?? 12);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const months = data ?? [];
    const payload = { count: months.length, months };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mppggukimaifwhuydwcq";
var mcp_default = defineMcp({
  name: "plano-do-milhao-mcp",
  title: "Plano do Milh\xE3o",
  version: "0.1.0",
  instructions: "Read-only access to the signed-in user's financial plan on Plano do Milh\xE3o: current plan and goal, active participants, investments (assets) with totals, and the recent monthly deposit history. Use get_plan_overview first to know the plan mode and goal, list_assets to inspect the portfolio, and list_monthly_tracking to review recent execution.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_plan_overview_default, list_assets_default, list_monthly_tracking_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.21.0-rc.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
