// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.21.0-rc.4";

// src/lib/mcp/tools/get-plan-overview.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.21.0-rc.4";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_plan_overview_default = defineTool({
  name: "get_plan_overview",
  title: "Vis\xE3o geral do plano",
  description: "Retorna o plano financeiro atual do usu\xE1rio autenticado: modo (individual ou casal), meta, prazo, aporte mensal e participantes ativos. Somente leitura.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Autentica\xE7\xE3o necess\xE1ria." }],
        structuredContent: { code: "not_authenticated" },
        isError: true
      };
    }
    const client = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: plan, error: planError } = await client.from("plans").select(
      "mode, goal_amount, goal_years, goal_purpose, initial_amount, monthly_contribution, onboarding_complete"
    ).eq("user_id", userId).order("created_at", { ascending: true }).limit(1).maybeSingle();
    if (planError) {
      console.error("mcp.get_plan_overview.plan_query_failed", planError);
      return {
        content: [{ type: "text", text: "N\xE3o foi poss\xEDvel carregar o plano. Tente novamente." }],
        structuredContent: { code: "read_failed" },
        isError: true
      };
    }
    if (!plan) {
      return {
        content: [
          {
            type: "text",
            text: "Nenhum plano financeiro foi encontrado para esta conta. Verifique se voc\xEA conectou a mesma conta usada no Plano do Milh\xE3o. Se conectou a conta errada, desvincule o conector no ChatGPT/Claude e conecte novamente com a conta correta."
          }
        ],
        structuredContent: {
          code: "no_plan",
          hint: "wrong_or_new_account",
          message: "Nenhum plano encontrado para o usu\xE1rio autenticado. Provavelmente \xE9 uma conta diferente da usada no app, ou o plano ainda n\xE3o foi criado."
        }
      };
    }
    const { data: planIdRow } = await client.from("plan_members").select("plan_id").eq("user_id", userId).limit(1).maybeSingle();
    const { data: members, error: membersError } = await client.from("plan_members").select("name, role, is_primary, age").eq("plan_id", planIdRow?.plan_id ?? "").eq("is_active", true).order("is_primary", { ascending: false });
    if (membersError) {
      console.error("mcp.get_plan_overview.members_query_failed", membersError);
      return {
        content: [{ type: "text", text: "N\xE3o foi poss\xEDvel carregar os participantes do plano. Tente novamente." }],
        structuredContent: { code: "read_failed" },
        isError: true
      };
    }
    const structured = {
      mode: plan.mode,
      goal_amount: plan.goal_amount,
      goal_years: plan.goal_years,
      goal_purpose: plan.goal_purpose,
      initial_amount: plan.initial_amount,
      monthly_contribution: plan.monthly_contribution,
      onboarding_complete: plan.onboarding_complete,
      members: members ?? []
    };
    const memberNames = (members ?? []).map((m) => m.name).filter(Boolean).join(", ");
    const summaryText = `Plano ${plan.mode === "casal" ? "de casal" : "individual"} \u2014 meta R$ ${Number(plan.goal_amount ?? 0).toLocaleString("pt-BR")} em ${plan.goal_years ?? "?"} anos, aporte mensal R$ ${Number(plan.monthly_contribution ?? 0).toLocaleString("pt-BR")}` + (memberNames ? `. Participantes: ${memberNames}.` : ".");
    return {
      content: [{ type: "text", text: summaryText }],
      structuredContent: structured
    };
  }
});

// src/lib/mcp/tools/list-assets.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.21.0-rc.4";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_assets_default = defineTool2({
  name: "list_assets",
  title: "Listar investimentos",
  description: "Lista os investimentos ativos do usu\xE1rio autenticado (tipo, institui\xE7\xE3o, valor aplicado, valor atual, bucket, FGC e liquidez) com totais. Somente leitura.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Autentica\xE7\xE3o necess\xE1ria." }],
        structuredContent: { code: "not_authenticated" },
        isError: true
      };
    }
    const { data, error } = await supabaseForUser2(ctx).from("assets").select(
      "asset_type, asset_subtype, ticker_or_name, institution, conglomerate, bucket, has_fgc, has_sovereign_guarantee, liquidity_type, invested_amount, current_amount, maturity_date"
    ).eq("user_id", ctx.getUserId()).eq("is_active", true).order("current_amount", { ascending: false });
    if (error) {
      console.error("mcp.list_assets.query_failed", error);
      return {
        content: [{ type: "text", text: "N\xE3o foi poss\xEDvel carregar os investimentos. Tente novamente." }],
        structuredContent: { code: "read_failed" },
        isError: true
      };
    }
    const assets = data ?? [];
    const total_invested = assets.reduce((sum, a) => sum + Number(a.invested_amount ?? 0), 0);
    const total_current = assets.reduce((sum, a) => sum + Number(a.current_amount ?? 0), 0);
    const payload = { count: assets.length, total_invested, total_current, assets };
    const summaryText = `${assets.length} investimento(s) ativo(s). Aplicado: R$ ${total_invested.toLocaleString("pt-BR")} \xB7 Atual: R$ ${total_current.toLocaleString("pt-BR")}.`;
    return {
      content: [{ type: "text", text: summaryText }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-monthly-tracking.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.21.0-rc.4";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_monthly_tracking_default = defineTool3({
  name: "list_monthly_tracking",
  title: "Listar aportes mensais",
  description: "Retorna os meses mais recentes do acompanhamento de aportes do usu\xE1rio autenticado (m\xEAs, planejado, realizado, d\xE9ficit e status). Somente leitura.",
  inputSchema: {
    limit: z.number().int().min(1).max(60).optional().describe("Quantos meses recentes retornar (1 a 60). Padr\xE3o: 12.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Autentica\xE7\xE3o necess\xE1ria." }],
        structuredContent: { code: "not_authenticated" },
        isError: true
      };
    }
    const { data, error } = await supabaseForUser3(ctx).from("monthly_tracking").select("month_key, year, month, planned_total, actual_total, shortfall, status, notes").eq("user_id", ctx.getUserId()).order("month_key", { ascending: false }).limit(limit ?? 12);
    if (error) {
      console.error("mcp.list_monthly_tracking.query_failed", error);
      return {
        content: [{ type: "text", text: "N\xE3o foi poss\xEDvel carregar o hist\xF3rico mensal. Tente novamente." }],
        structuredContent: { code: "read_failed" },
        isError: true
      };
    }
    const months = data ?? [];
    const payload = { count: months.length, months };
    const summaryText = `${months.length} m\xEAs(es) de acompanhamento retornado(s).`;
    return {
      content: [{ type: "text", text: summaryText }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mppggukimaifwhuydwcq";
var mcp_default = defineMcp({
  name: "plano-do-milhao-mcp",
  title: "Plano do Milh\xE3o",
  version: "0.1.0",
  instructions: "Read-only access to the signed-in user's financial plan on Plano do Milh\xE3o: current plan and goal, active participants, investments (assets) with totals, and the recent monthly deposit history. Use get_plan_overview first to know the plan mode and goal, list_assets to inspect the portfolio, and list_monthly_tracking to review recent execution.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_plan_overview_default, list_assets_default, list_monthly_tracking_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.21.0-rc.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
